### PR TITLE
Removed shutdown servers from IP list

### PR DESCRIPTION
**Pull request by Column01**
Removed some servers that got shutdown on 10/16/2018

### CODE REVIEW

**Comment by Aiidoneus** [comment]
Thanks!

**Comment by Column01** [comment]
Hey, when does it update on the wiki? Cause I have another commit that never got added to the wiki that fixed Enigmatica's IP and version

**Comment by Slind14** [comment]
It should automatically. Somehow it was stuck. I have started it manually now.

**Comment by Column01** [comment]
Appears to still be outdated
https://i.imgur.com/UYXKE7N.png

**Comment by Slind14** [comment]
Seems to be your cache:
image

**Comment by Column01** [comment]
Ah ok. Cleared the cache and it updated. My bad

**Pull request merged**
